// document actions
export const ADD_DOCUMENT = 'ADD_DOCUMENT'; 
// annotation actions
export const ADD_ANNOTATIONS = 'ADD_ANNOTATIONS';
export const ADD_ANNOTATION = 'ADD_ANNOTATION';
export const EDIT_ANNOTATION = 'EDIT_ANNOTATION';
export const REMOVE_ANNOTATION = 'REMOVE_ANNOTATION';
export const FILTER_ANNOTATIONS = 'FILTER_ANNOTATIONS';
export const TOGGLE_HIGHLIGHTS = 'TOGGLE_HIGHLIGHTS';
// category actions
export const ADD_CATEGORY = 'ADD_CATEGORY';

export default {
  ADD_DOCUMENT,
  ADD_ANNOTATIONS,
  ADD_ANNOTATION,
  EDIT_ANNOTATION,
  REMOVE_ANNOTATION,
  FILTER_ANNOTATIONS,
  TOGGLE_HIGHLIGHTS,
  ADD_CATEGORY,
};
